export const exception = () => console.log("EXCEPTION");
